### ISSUE TITLE
Zero-sized disks cause divide by zero exception

### ISSUE THREAD

**Issue by jmbeach** [JulianChow94/Windows-screenFetch#14]
For whatever reason, I have disks or partitions with no space on them, such as drives created by Daemon Tools Lite to mount ISO files.

This causes a divide by zero exception when trying to calculate disk usage in Data.psm1.

**Comment by tommasov** [comment]
This version is still affected https://www.powershellgallery.com/packages/windows-screenfetch/1.0.2

**Comment by JulianChow94** [comment]
@tommasov i should have time to update the version this weekend

**Comment by Sharpz7** [comment]
@JulianChow94 This is still a problem... Could I just merge it in?

**Comment by DRSDavidSoft** [comment]
<img width="568" alt="divide by zero" src="https://user-images.githubusercontent.com/4673812/53051035-14d67c00-34b0-11e9-9295-6ce92e8a82ca.png">

### Line 174
```powershell
            $FreeDiskPercent = ($FreeDiskSizeGB / $DiskSizeGB) * 100;
```

### Line 178
```powershell
            $UsedDiskPercent = ($UsedDiskSizeGB / $DiskSizeGB) * 100;
```

**Comment by jmbeach** [comment]
The fix was merged. I would just clone the script and use it directly. It's actually surprisingly tricky to upload a package to the powershell gallery

**Comment by ChildishGiant** [comment]
I just installed from the PowerShell Gallery and still had this issue

**Comment by Ezroosp** [comment]
@DRSDavidSoft <p><i>Estou com o mesmo problema</i><strong>Tentativa de divisão por zero.</strong></p><p>Você conseguiu solucionar o erro?</p>

**Comment by Nekuskus** [comment]
This is still an issue, for ext4 disks too. I will try to fix it and make a pull request.
